import { Injectable, Logger } from '@nestjs/common';
import {
  ProviderAdapter,
  ProviderEventInput,
  KnowledgeItem,
  EyeType,
  Provider,
} from '../../contracts';
import { MicrosoftGraphChatMessage, MicrosoftGraphEvent } from '../types/teams.types';

/**
 * Microsoft Teams implementation of ProviderAdapter.
 * Normalizes raw Microsoft Graph ChatMessage payloads into KnowledgeItems.
 */
@Injectable()
export class TeamsAdapterService implements ProviderAdapter {
  private readonly logger = new Logger(TeamsAdapterService.name);

  /**
   * Normalizes a raw Microsoft Graph ChatMessage or Event payload into KnowledgeItem(s).
   */
  normalizeEvent(input: ProviderEventInput): KnowledgeItem[] {
    const payload = input.rawPayload as any;

    if (!payload || !payload.id) {
      this.logger.debug('Ignoring invalid or empty event payload');
      return [];
    }

    if (payload.isOnlineMeeting !== undefined) {
      return this.normalizeMeetingEvent(input, payload as MicrosoftGraphEvent);
    } else {
      return this.normalizeChatEvent(input, payload as MicrosoftGraphChatMessage);
    }
  }

  private normalizeChatEvent(input: ProviderEventInput, event: MicrosoftGraphChatMessage): KnowledgeItem[] {

    // Determine the resource ID and context
    let externalResourceId = '';
    let contextLocation = '';
    
    if (event.channelIdentity?.channelId) {
      externalResourceId = event.channelIdentity.channelId;
      contextLocation = `Teams Channel ${event.channelIdentity.channelId}`;
    } else if (event.chatId) {
      externalResourceId = event.chatId;
      contextLocation = `Teams Chat ${event.chatId}`;
    } else {
      // Fallback
      externalResourceId = 'unknown';
      contextLocation = 'Microsoft Teams';
    }

    const authorId = event.from?.user?.id || event.from?.application?.id || 'system';
    
    // We treat deleted messages gracefully
    if (event.deletedDateTime) {
       // Aian can handle deletions by keeping the event but stripping content,
       // or returning it with empty content. For now we just process it.
    }

    return [
      {
        id: undefined as any, // Auto-generated by DB
        organizationId: input.organizationId,
        eyeType: EyeType.CHAT,
        provider: Provider.TEAMS,
        sourceType: 'message',
        eventType: 'message',
        externalResourceId,
        externalEventId: event.id, 
        parentExternalResourceId: event.replyToId || null,
        title: null,
        // Optional: Strip HTML if required by Aian text pipeline, but generally Aian preserves some basic html or text content
        content: event.body?.content || '', 
        author: {
          externalId: authorId,
          name: event.from?.user?.displayName || event.from?.application?.displayName,
        },
        participants: authorId !== 'system' ? [{ externalId: authorId }] : [],
        contextLocation,
        sourceUrl: event.webUrl || null,
        occurredAt: new Date(event.createdDateTime),
        receivedAt: new Date(),
        visibility: 'ORGANIZATION',
        metadata: {
          teamId: event.channelIdentity?.teamId,
          messageType: event.messageType,
          lastModifiedDateTime: event.lastModifiedDateTime,
          deletedDateTime: event.deletedDateTime,
          contentType: event.body?.contentType,
        },
        rawPayloadReference: input.rawEventReference,
        version: null,
      },
    ];
  }

  private normalizeMeetingEvent(input: ProviderEventInput, event: MicrosoftGraphEvent): KnowledgeItem[] {
    const externalResourceId = event.teamIdentity?.teamId || 'unknown';
    const contextLocation = `Teams Team ${externalResourceId}`;
    
    const authorId = event.organizer?.emailAddress?.address || 'system';
    const authorName = event.organizer?.emailAddress?.name;

    const participants = (event.attendees || []).map(att => ({
      externalId: att.emailAddress.address,
      name: att.emailAddress.name,
    }));

    if (authorId !== 'system' && !participants.some(p => p.externalId === authorId)) {
      participants.push({ externalId: authorId, name: authorName as string });
    }

    return [
      {
        id: undefined as any,
        organizationId: input.organizationId,
        eyeType: EyeType.MEETING,
        provider: Provider.TEAMS,
        sourceType: 'meeting',
        eventType: 'meeting',
        externalResourceId,
        externalEventId: event.id,
        parentExternalResourceId: null,
        title: event.subject || 'Untitled Meeting',
        content: '', 
        author: {
          externalId: authorId,
          name: authorName,
        },
        participants,
        contextLocation,
        sourceUrl: event.onlineMeeting?.joinUrl || event.webLink || null,
        occurredAt: event.start?.dateTime ? new Date(event.start.dateTime) : new Date(event.createdDateTime),
        receivedAt: new Date(),
        visibility: 'ORGANIZATION',
        metadata: {
          teamId: event.teamIdentity?.teamId,
          isOnlineMeeting: event.isOnlineMeeting,
          onlineMeetingProvider: event.onlineMeetingProvider,
          start: event.start,
          end: event.end,
          type: event.type,
          createdDateTime: event.createdDateTime,
          lastModifiedDateTime: event.lastModifiedDateTime,
        },
        rawPayloadReference: input.rawEventReference,
        version: null,
      },
    ];
  }

  /**
   * Generates a globally unique idempotency key for a Teams message or meeting.
   */
  getIdempotencyKey(item: KnowledgeItem): string {
    if (item.eyeType === EyeType.MEETING) {
      return `teams:${item.organizationId}:${item.externalResourceId}:meeting:${item.externalEventId}`;
    }
    return `teams:${item.organizationId}:${item.externalResourceId}:${item.externalEventId}`;
  }

  /**
   * Extracts the resource ID from the raw payload for webhook routing.
   */
  getExternalResourceId(input: ProviderEventInput): string {
    const payload = input.rawPayload as any;
    if (payload.isOnlineMeeting !== undefined) {
      return payload.teamIdentity?.teamId || '';
    }
    const event = payload as MicrosoftGraphChatMessage;
    return event.channelIdentity?.channelId || event.chatId || '';
  }

  /**
   * Extracts the external event ID from the raw payload.
   */
  getExternalEventId(input: ProviderEventInput): string {
    const payload = input.rawPayload as any;
    return payload.id || '';
  }
}
