import { Injectable, Logger } from '@nestjs/common';
import {
  ProviderAdapter,
  ProviderEventInput,
  KnowledgeItem,
  EyeType,
  Provider,
} from '../../contracts';
import { MicrosoftGraphChatMessage } from '../types/teams.types';

/**
 * Microsoft Teams implementation of ProviderAdapter.
 * Normalizes raw Microsoft Graph ChatMessage payloads into KnowledgeItems.
 */
@Injectable()
export class TeamsAdapterService implements ProviderAdapter {
  private readonly logger = new Logger(TeamsAdapterService.name);

  /**
   * Normalizes a raw Microsoft Graph ChatMessage payload into KnowledgeItem(s).
   */
  normalizeEvent(input: ProviderEventInput): KnowledgeItem[] {
    const event = input.rawPayload as unknown as MicrosoftGraphChatMessage;

    if (!event || !event.id) {
      this.logger.debug('Ignoring invalid or empty event payload');
      return [];
    }

    // Determine the resource ID and context
    let externalResourceId = '';
    let contextLocation = '';
    
    if (event.channelIdentity?.channelId) {
      externalResourceId = event.channelIdentity.channelId;
      contextLocation = `Teams Channel ${event.channelIdentity.channelId}`;
    } else if (event.chatId) {
      externalResourceId = event.chatId;
      contextLocation = `Teams Chat ${event.chatId}`;
    } else {
      // Fallback
      externalResourceId = 'unknown';
      contextLocation = 'Microsoft Teams';
    }

    const authorId = event.from?.user?.id || event.from?.application?.id || 'system';
    
    // We treat deleted messages gracefully
    if (event.deletedDateTime) {
       // Aian can handle deletions by keeping the event but stripping content,
       // or returning it with empty content. For now we just process it.
    }

    return [
      {
        id: undefined as any, // Auto-generated by DB
        organizationId: input.organizationId,
        eyeType: EyeType.CHAT,
        provider: Provider.TEAMS,
        sourceType: 'message',
        eventType: 'message',
        externalResourceId,
        externalEventId: event.id, 
        parentExternalResourceId: event.replyToId || null,
        title: null,
        // Optional: Strip HTML if required by Aian text pipeline, but generally Aian preserves some basic html or text content
        content: event.body?.content || '', 
        author: {
          externalId: authorId,
          name: event.from?.user?.displayName || event.from?.application?.displayName,
        },
        participants: authorId !== 'system' ? [{ externalId: authorId }] : [],
        contextLocation,
        sourceUrl: event.webUrl || null,
        occurredAt: new Date(event.createdDateTime),
        receivedAt: new Date(),
        visibility: 'ORGANIZATION',
        metadata: {
          teamId: event.channelIdentity?.teamId,
          messageType: event.messageType,
          lastModifiedDateTime: event.lastModifiedDateTime,
          deletedDateTime: event.deletedDateTime,
          contentType: event.body?.contentType,
        },
        rawPayloadReference: input.rawEventReference,
        version: null,
      },
    ];
  }

  /**
   * Generates a globally unique idempotency key for a Teams message.
   */
  getIdempotencyKey(item: KnowledgeItem): string {
    return `teams:${item.organizationId}:${item.externalResourceId}:${item.externalEventId}`;
  }

  /**
   * Extracts the resource ID from the raw payload for webhook routing.
   */
  getExternalResourceId(input: ProviderEventInput): string {
    const event = input.rawPayload as unknown as MicrosoftGraphChatMessage;
    return event.channelIdentity?.channelId || event.chatId || '';
  }

  /**
   * Extracts the external event ID from the raw payload.
   */
  getExternalEventId(input: ProviderEventInput): string {
    const event = input.rawPayload as unknown as MicrosoftGraphChatMessage;
    return event.id || '';
  }
}
