/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-unused-vars */
import { Injectable, OnModuleInit, Optional } from '@nestjs/common';
import { ResilienceService } from '../core/resilience.service';
import { SkillRegistryService } from '../core/registry.service';
import { SkillContext, SkillResult } from '../core/types';
import { GenerateReportInputSchema } from './schemas';
import { RetrievalPipelineService } from '../../retrieval/retrieval-pipeline.service';
import { AnswerGenerationService } from '../../retrieval/services/answer-generation.service';
import { JiraClientService } from '../../integrations/jira/services/jira-client.service';
import { TrelloClientService } from '../../integrations/trello/services/trello-client.service';
import { ZoomClientService, MeetingType } from '../../integrations/zoom/zoom-client.service';
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class ReportingSkill implements OnModuleInit {
  constructor(
    private readonly retrievalPipeline: RetrievalPipelineService,
    private readonly answerGeneration: AnswerGenerationService,
    private readonly jiraClient: JiraClientService,
    @Optional() private readonly trelloClient: TrelloClientService,
    private readonly zoomClient: ZoomClientService,
    private readonly prisma: PrismaService,
    private readonly resilienceService: ResilienceService,
    private readonly registry: SkillRegistryService,
  ) {}

  onModuleInit() {
    this.registry.register({
      name: 'ReportingSkill.generateReport',
      description:
        'Generates structured markdown reports (Daily, Weekly, Performance, or Planning) by aggregating Jira or Trello tasks, Zoom meetings, and cross-platform Knowledge Graph context.',
      schema: GenerateReportInputSchema,
      destructive: false,
      requiredProviders: [],
      optionalProviders: ['JIRA', 'Jira', 'jira', 'TRELLO', 'Trello', 'trello', 'ZOOM', 'Zoom', 'zoom'],
      handler: (ctx: SkillContext, input: any) => this.generateReport(ctx, input),
    });
  }

  async generateReport(ctx: SkillContext, input: any): Promise<SkillResult<any>> {
    const parsed = GenerateReportInputSchema.safeParse(input);
    if (!parsed.success) {
      return {
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: parsed.error.message,
          retryable: false,
        },
        meta: {
          skill: 'ReportingSkill',
          provider: 'multiple',
          durationMs: 0,
          idempotencyKey: ctx.idempotencyKey,
        },
      };
    }

    return this.resilienceService.execute(
      ctx,
      'ReportingSkill',
      'generateReport',
      'multiple',
      parsed.data,
      async () => {
        const { reportType = 'daily', scope, targetUser, timeframe, sections } = parsed.data;
        const type = reportType || 'daily';
        const activeSections = sections || ['tasks', 'meetings', 'knowledge'];

        let fullReport = '';

        switch (type) {
          case 'weekly':
            fullReport = await this.buildWeeklyReport(ctx, scope, timeframe, activeSections);
            break;
          case 'performance':
            fullReport = await this.buildPerformanceReport(ctx, scope, targetUser, timeframe, activeSections);
            break;
          case 'planning':
            fullReport = await this.buildPlanningReport(ctx, scope, timeframe, activeSections);
            break;
          case 'daily':
          default:
            fullReport = await this.buildDailyReport(ctx, scope, timeframe, activeSections);
            break;
        }

        // Apply Slack ~3900 characters safety threshold
        if (fullReport.length > 3900) {
          fullReport = fullReport.substring(0, 3900) + '\n\n*(Report truncated due to length limits)*';
        }

        return { reportMarkdown: fullReport };
      },
    );
  }

  /**
   * Daily Status Report
   */
  private async buildDailyReport(
    ctx: SkillContext,
    scope: string,
    timeframe: any,
    sections: string[],
  ): Promise<string> {
    const fromStr = timeframe?.from ?? new Date(Date.now() - 86400000).toISOString().split('T')[0];
    const toStr = timeframe?.to ?? new Date().toISOString().split('T')[0];

    const tasksMarkdown = sections.includes('tasks')
      ? await this.fetchTasksSection(ctx, `updated >= -1d`, 'Daily Tasks (Last 24h)', scope)
      : '';

    const meetingsMarkdown = sections.includes('meetings')
      ? await this.fetchZoomMeetingsSection(ctx, 'Daily Meetings')
      : '';

    const knowledgeMarkdown = sections.includes('knowledge')
      ? await this.fetchKnowledgeContextSection(ctx, `${scope} daily updates and key decisions made today`)
      : '';

    return `# Daily Report: ${scope}
*Period: ${fromStr} — ${toStr}*

${tasksMarkdown}

${meetingsMarkdown}

${knowledgeMarkdown}

---
*Generated by AIAN ReportingSkill*`;
  }

  /**
   * Weekly Sprint Summary Report
   */
  private async buildWeeklyReport(
    ctx: SkillContext,
    scope: string,
    timeframe: any,
    sections: string[],
  ): Promise<string> {
    const fromStr = timeframe?.from ?? new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0];
    const toStr = timeframe?.to ?? new Date().toISOString().split('T')[0];

    const tasksMarkdown = sections.includes('tasks')
      ? await this.fetchTasksSection(ctx, `updated >= -7d`, 'Weekly Sprint Tasks', scope)
      : '';

    const meetingsMarkdown = sections.includes('meetings')
      ? await this.fetchZoomMeetingsSection(ctx, 'Weekly Meetings & Reviews')
      : '';

    const knowledgeMarkdown = sections.includes('knowledge')
      ? await this.fetchKnowledgeContextSection(ctx, `${scope} weekly sprint accomplishments and architectural changes`)
      : '';

    return `# Weekly Report: ${scope}
*Period: ${fromStr} — ${toStr}*

${tasksMarkdown}

${meetingsMarkdown}

${knowledgeMarkdown}

---
*Generated by AIAN ReportingSkill*`;
  }

  /**
   * Individual Performance & Activity Report
   */
  private async buildPerformanceReport(
    ctx: SkillContext,
    scope: string,
    targetUser?: string | null,
    timeframe?: any,
    sections?: string[],
  ): Promise<string> {
    const userName = targetUser ?? 'Team Member';
    const fromStr = timeframe?.from ?? 'Start of Month';
    const toStr = timeframe?.to ?? new Date().toISOString().split('T')[0];

    const jql = targetUser
      ? `assignee ~ "${targetUser}" OR text ~ "${targetUser}"`
      : `updated >= -7d`;

    const tasksMarkdown = await this.fetchTasksSection(
      ctx,
      jql,
      `Assigned Tasks & Ticket Contributions (${userName})`,
      userName,
    );

    const meetingsMarkdown = await this.fetchZoomMeetingsSection(
      ctx,
      `Meetings & Review Participations (${userName})`,
    );

    const knowledgeMarkdown = await this.fetchKnowledgeContextSection(
      ctx,
      `Detailed contributions, pull requests, commits, and activity by ${userName} in ${scope}`,
    );

    return `# Performance Report: ${userName}
*Scope: ${scope} | Period: ${fromStr} — ${toStr}*

### Summary of Activity & Contributions
This report aggregates Jira and Trello ticket assignments, Zoom meeting participations, and cross-platform Knowledge Graph commits/discussions for **${userName}**.

${tasksMarkdown}

${meetingsMarkdown}

${knowledgeMarkdown}

---
*Generated by AIAN ReportingSkill*`;
  }

  /**
   * Today's Planning & Roadmap Report
   */
  private async buildPlanningReport(
    ctx: SkillContext,
    scope: string,
    timeframe: any,
    sections: string[],
  ): Promise<string> {
    const todayStr = new Date().toISOString().split('T')[0];

    const tasksMarkdown = sections.includes('tasks')
      ? await this.fetchTasksSection(
          ctx,
          `status in ("To Do", "In Progress", "In Review")`,
          'Active & Pending Tasks (Roadmap)',
          scope,
        )
      : '';

    const meetingsMarkdown = sections.includes('meetings')
      ? await this.fetchZoomMeetingsSection(ctx, "Today's Scheduled Meetings")
      : '';

    const knowledgeMarkdown = sections.includes('knowledge')
      ? await this.fetchKnowledgeContextSection(ctx, `${scope} active action items and open roadmap targets for today`)
      : '';

    return `# Planning & Roadmap Report: ${scope}
*Target Date: ${todayStr}*

${tasksMarkdown}

${meetingsMarkdown}

${knowledgeMarkdown}

---
*Generated by AIAN ReportingSkill*`;
  }

  // ── Helper Data Fetchers ──────────────────────────────────────────────────

  /**
   * Fetches tasks from Jira OR Trello depending on active connection.
   */
  private async fetchTasksSection(
    ctx: SkillContext,
    jql: string,
    title: string,
    userFilter?: string,
  ): Promise<string> {
    // 1. Try Jira Connection
    try {
      const jiraConnection =
        ctx?.connections?.['JIRA'] ||
        ctx?.connections?.['Jira'] ||
        ctx?.connections?.['jira'] ||
        (await this.prisma.providerConnection.findFirst({
          where: {
            organizationEyeId: ctx.organizationId,
            provider: { key: 'jira' },
            status: 'connected',
          },
        }));

      if (jiraConnection) {
        const searchResult = await this.jiraClient.searchIssues(ctx.organizationId, jql, 15);
        const issues = searchResult?.issues || [];

        if (Array.isArray(issues) && issues.length > 0) {
          const tableRows = issues
            .map((i: any) => {
              const key = i.key || 'N/A';
              const summary = i.fields?.summary || 'No summary';
              const status = i.fields?.status?.name || 'To Do';
              const assignee = i.fields?.assignee?.displayName || 'Unassigned';
              return `| ${key} | ${summary} | ${status} | ${assignee} |`;
            })
            .join('\n');

          return `## ${title}\n| Key | Summary | Status | Assignee |\n|---|---|---|---|\n${tableRows}`;
        }
      }
    } catch (err: any) {
      // Fallback to Trello if Jira fails
    }

    // 2. Try Trello Connection
    try {
      const trelloConnection =
        ctx?.connections?.['TRELLO'] ||
        ctx?.connections?.['Trello'] ||
        ctx?.connections?.['trello'] ||
        (await this.prisma.providerConnection.findFirst({
          where: {
            organizationEyeId: ctx.organizationId,
            provider: { key: 'trello' },
            status: 'connected',
          },
        }));

      if (trelloConnection && this.trelloClient) {
        const boards = await this.trelloClient.getBoards(trelloConnection as any);
        if (Array.isArray(boards) && boards.length > 0) {
          const mainBoard = boards[0];
          const cards = await this.trelloClient.listTasks(ctx.organizationId, {
            boardName: mainBoard.name,
            maxResults: 15,
          });

          if (Array.isArray(cards) && cards.length > 0) {
            const tableRows = cards
              .slice(0, 15)
              .map((c: any) => {
                const key = c.id?.slice(-6) || 'Card';
                const summary = c.name || 'Untitled Card';
                const status = c.closed ? 'Archived' : 'Active';
                const assignee = userFilter || 'Team Member';
                return `| ${key} | ${summary} | ${status} | ${assignee} |`;
              })
              .join('\n');

            return `## ${title}\n| Key | Summary | Status | Assignee |\n|---|---|---|---|\n${tableRows}`;
          }
        }
      }
    } catch (err: any) {
      // Ignore provider error
    }

    return `## ${title}\n*No active tasks found in Jira or Trello.*`;
  }

  private async fetchZoomMeetingsSection(
    ctx: SkillContext,
    title: string,
  ): Promise<string> {
    try {
      const zoomConnection =
        ctx?.connections?.['ZOOM'] ||
        ctx?.connections?.['Zoom'] ||
        ctx?.connections?.['zoom'] ||
        (await this.prisma.providerConnection.findFirst({
          where: {
            organizationEyeId: ctx.organizationId,
            provider: { key: 'zoom' },
            status: 'connected',
          },
        }));

      if (!zoomConnection) {
        return `## ${title}\n*Zoom integration not connected.*`;
      }

      // Execute listMeetings via ZoomClientService
      const meetingsResult = await this.zoomClient.listMeetings(
        zoomConnection as any,
        MeetingType.Scheduled,
        10,
      );
      const meetings = meetingsResult?.resources || [];

      if (!Array.isArray(meetings) || meetings.length === 0) {
        return `## ${title}\n*No meetings recorded for this period.*`;
      }

      const tableRows = meetings
        .slice(0, 10)
        .map((m: any) => {
          const name = m.name || 'Untitled Meeting';
          const startTime = m.metadata?.start_time
            ? new Date(m.metadata.start_time).toLocaleString('en-US', {
                dateStyle: 'medium',
                timeStyle: 'short',
              })
            : 'N/A';
          const duration = m.metadata?.duration ? `${m.metadata.duration}m` : 'N/A';
          const host = m.metadata?.host_email || 'Host';
          return `| ${name} | ${startTime} | ${duration} | ${host} |`;
        })
        .join('\n');

      return `## ${title}\n| Topic | Date/Time | Duration | Host/Attendees |\n|---|---|---|---|\n${tableRows}`;
    } catch (err: any) {
      return `## ${title}\n*Error fetching Zoom meetings: ${err.message}*`;
    }
  }

  private async fetchKnowledgeContextSection(
    ctx: SkillContext,
    queryPrompt: string,
  ): Promise<string> {
    try {
      const retrievalResult = await this.retrievalPipeline.retrieveContext(
        ctx.organizationId,
        queryPrompt,
      );
      const contextString = retrievalResult?.contextString || '';

      if (!contextString) {
        return `## Knowledge Context\n*No relevant knowledge graph context found.*`;
      }

      const summaryAnswer = await this.answerGeneration.generateAnswer(
        ctx.organizationId,
        `Summarize the key developments, PRs, and architectural insights for: ${queryPrompt}`,
        contextString,
      );

      const sources: string[] = [];
      if (retrievalResult?.evidenceChains && Array.isArray(retrievalResult.evidenceChains)) {
        retrievalResult.evidenceChains.forEach((node: any) => {
          if (node?.name || node?.artifactId) {
            sources.push(node.name || node.artifactId);
          }
        });
      }

      const sourcesFormatted = sources.length > 0 ? Array.from(new Set(sources)).join(', ') : 'Knowledge Graph';

      return `## Knowledge Context\n${summaryAnswer}\n\n*Sources: ${sourcesFormatted}*`;
    } catch (err: any) {
      return `## Knowledge Context\n*Error generating knowledge summary: ${err.message}*`;
    }
  }
}